# Generated by Django 5.1.4 on 2025-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Model',
            fields=[
                ('company_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.IntegerField()),
            ],
        ),
    ]
