# Generated by Django 5.1.4 on 2025-01-08 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeder_Model',
            fields=[
                ('breeder_id', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('breeder_type', models.CharField(choices=[('BB', 'Boiler Breeder'), ('LB', 'Layer Breeder'), ('GB', 'Golden Breeder')], max_length=100)),
                ('breeder_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distributed_among_companies',
            fields=[
                ('medicine_id', models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type_of_chick', models.CharField(choices=[('BB', 'Boiler Breeder'), ('LB', 'Layer Breeder'), ('GB', 'Golden Breeder')], max_length=100)),
                ('total_number_of_chicks', models.IntegerField()),
                ('infacted_chicks', models.IntegerField()),
                ('diseased_chicks', models.IntegerField()),
                ('date_of_departure', models.DateField(editable=False)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company_model')),
            ],
        ),
    ]
