# Generated by Django 5.1.4 on 2025-01-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeder_model',
            name='breeder_type',
            field=models.CharField(choices=[('Boiler Breeder', 'Boiler Breeder'), ('Layer Breeder', 'Layer Breeder'), ('Golden Breeder', 'Golden Breeder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='distributed_among_companies',
            name='type_of_chick',
            field=models.CharField(choices=[('Boiler Breeder', 'Boiler Breeder'), ('Layer Breeder', 'Layer Breeder'), ('Golden Breeder', 'Golden Breeder')], max_length=100),
        ),
    ]
