# Generated by Django 5.1.4 on 2025-01-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_chick_model_breeder_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chick_model',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feed_model',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicine_model',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
