# Generated by Django 5.1.4 on 2025-11-26 03:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('breeder_type', models.CharField(blank=True, choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('severity', models.PositiveSmallIntegerField(help_text='1=Low 5=High', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, max_length=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('breeder_type', models.CharField(choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('breeder_type', models.CharField(blank=True, choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChickBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeder_type', models.CharField(choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('hatch_date', models.DateField()),
                ('initial_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_count', models.PositiveIntegerField(blank=True, help_text='Current live count', null=True)),
                ('farm_location', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, help_text='Supplier or hatchery', max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DECEASED', 'Deceased'), ('CULLED', 'Culled')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Chick Batches',
                'ordering': ['-hatch_date'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_detected', models.DateField(default=django.utils.timezone.now)),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_cases', to='products.chickbatch')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='products.diseasecatalog')),
            ],
            options={
                'ordering': ['-date_detected'],
            },
        ),
        migrations.CreateModel(
            name='FeedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_schedules', to='products.chickbatch')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_feeds', to='products.feedformula')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_date', models.DateField(default=django.utils.timezone.now)),
                ('diseased_count', models.PositiveIntegerField(default=0)),
                ('mortality_count', models.PositiveIntegerField(default=0)),
                ('average_weight_g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='products.chickbatch')),
            ],
            options={
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('FEED', 'Feed'), ('MEDICINE', 'Medicine'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('breeder_type', models.CharField(blank=True, choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('unit', models.CharField(default='unit', max_length=40)),
                ('stock_on_hand', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_administered', models.DateField(default=django.utils.timezone.now)),
                ('dosage', models.CharField(blank=True, max_length=80)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='products.chickbatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='products.medicineproduct')),
            ],
            options={
                'ordering': ['-date_administered'],
            },
        ),
        migrations.AddIndex(
            model_name='chickbatch',
            index=models.Index(fields=['company', 'breeder_type'], name='products_ch_company_6b08bc_idx'),
        ),
        migrations.AddIndex(
            model_name='chickbatch',
            index=models.Index(fields=['company', 'hatch_date'], name='products_ch_company_536597_idx'),
        ),
        migrations.AddIndex(
            model_name='chickbatch',
            index=models.Index(fields=['company', 'status'], name='products_ch_company_b40cda_idx'),
        ),
        migrations.AddIndex(
            model_name='diseasecase',
            index=models.Index(fields=['status'], name='products_di_status_905ff8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='healthcheck',
            unique_together={('batch', 'check_date')},
        ),
        migrations.AddIndex(
            model_name='inventoryproduct',
            index=models.Index(fields=['company', 'sku'], name='products_in_company_9bb3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryproduct',
            index=models.Index(fields=['company', 'category'], name='products_in_company_084a28_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryproduct',
            index=models.Index(fields=['company', 'is_active'], name='products_in_company_1abd98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryproduct',
            unique_together={('company', 'sku')},
        ),
    ]
