# Generated by Django 5.1.4 on 2025-12-04 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecatalog',
            name='morality_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage (e.g., 12.5 for 12.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='diseasecatalog',
            name='prevention',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='diseasecatalog',
            name='symptoms',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='diseasecatalog',
            name='treatment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
