# Generated by Django 5.1.4 on 2025-01-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chick_model',
            name='breeder_type',
            field=models.CharField(choices=[('Boiler Breeder', 'Boiler Breeder'), ('Layer Breeder', 'Layer Breeder'), ('Golden Breeder', 'Golden Breeder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='disease_model',
            name='disease_in_type_of_breed',
            field=models.CharField(choices=[('Boiler Breeder', 'Boiler Breeder'), ('Layer Breeder', 'Layer Breeder'), ('Golden Breeder', 'Golden Breeder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feed_model',
            name='feed_type',
            field=models.CharField(choices=[('Boiler Breeder', 'Boiler Breeder'), ('Layer Breeder', 'Layer Breeder'), ('Golden Breeder', 'Golden Breeder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine_model',
            name='medicine_for_type_breed',
            field=models.CharField(choices=[('Boiler Breeder', 'Boiler Breeder'), ('Layer Breeder', 'Layer Breeder'), ('Golden Breeder', 'Golden Breeder')], max_length=100),
        ),
    ]
