# Generated by Django 5.1.4 on 2025-11-24 19:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_chick_model_date_feed_model_date_medicine_model_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeder_type', models.CharField(choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('hatch_date', models.DateField()),
                ('initial_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('farm_location', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, help_text='Supplier or hatchery', max_length=120)),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['-hatch_date'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_detected', models.DateField(default=django.utils.timezone.now)),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['-date_detected'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('breeder_type', models.CharField(blank=True, choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('severity', models.PositiveSmallIntegerField(help_text='1=Low 5=High', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, max_length=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('breeder_type', models.CharField(choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_date', models.DateField(default=django.utils.timezone.now)),
                ('diseased_count', models.PositiveIntegerField(default=0)),
                ('mortality_count', models.PositiveIntegerField(default=0)),
                ('average_weight_g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('FEED', 'Feed'), ('MEDICINE', 'Medicine'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('breeder_type', models.CharField(blank=True, choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('unit', models.CharField(default='unit', max_length=40)),
                ('stock_on_hand', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('breeder_type', models.CharField(blank=True, choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('GOLDEN', 'Golden')], max_length=16)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('reference_code', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_uid', models.CharField(help_text='Unique RFID tag identifier', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment')], max_length=8)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_administered', models.DateField(default=django.utils.timezone.now)),
                ('dosage', models.CharField(blank=True, max_length=80)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['-date_administered'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Chick_Model',
        ),
        migrations.DeleteModel(
            name='Disease_Model',
        ),
        migrations.DeleteModel(
            name='Feed_Model',
        ),
        migrations.DeleteModel(
            name='Medicine_Model',
        ),
        migrations.AddIndex(
            model_name='chickbatch',
            index=models.Index(fields=['breeder_type'], name='products_ch_breeder_6d9d33_idx'),
        ),
        migrations.AddIndex(
            model_name='chickbatch',
            index=models.Index(fields=['hatch_date'], name='products_ch_hatch_d_485a7b_idx'),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_cases', to='products.chickbatch'),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='products.diseasecatalog'),
        ),
        migrations.AddField(
            model_name='feedschedule',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_schedules', to='products.chickbatch'),
        ),
        migrations.AddField(
            model_name='feedschedule',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_feeds', to='products.feedformula'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='products.chickbatch'),
        ),
        migrations.AddIndex(
            model_name='inventoryproduct',
            index=models.Index(fields=['sku'], name='products_in_sku_b058b3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryproduct',
            index=models.Index(fields=['category'], name='products_in_categor_e8ac07_idx'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.inventoryproduct'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchaseorder'),
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='assigned_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_tags', to='products.chickbatch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.inventoryproduct'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='products.chickbatch'),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='administered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='products.chickbatch'),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='products.medicineproduct'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='products.vendor'),
        ),
        migrations.AddIndex(
            model_name='diseasecase',
            index=models.Index(fields=['status'], name='products_di_status_905ff8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='healthcheck',
            unique_together={('batch', 'check_date')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('purchase_order', 'product')},
        ),
        migrations.AddIndex(
            model_name='rfidtag',
            index=models.Index(fields=['tag_uid'], name='products_rf_tag_uid_94166d_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidtag',
            index=models.Index(fields=['is_active'], name='products_rf_is_acti_075dd8_idx'),
        ),
    ]
